### PR TITLE
Add Python 3.6 to Travis

### PR DESCRIPTION
**Pull request by gliptak**

### CODE REVIEW

**Comment by tk0miya** [comment]
Please check the result of Travis. It seems failed.

**Comment by gliptak** [comment]
https://github.com/travis-ci/travis-ci/issues/8363

**Comment by gliptak** [comment]
@tk0miya I implemented a workaround.

**Comment by gliptak** [comment]
@tk0miya Please review. Thanks

**Comment by tk0miya** [comment]
LGTM, thanks!

**Pull request merged**
